Rethrow the error caught when builder fails
alan-turing-institute/MLJFlux.jl pull request #238
Opened 2023-09-04 03:00 UTC by ablaom

Closes #237

There is presently a `throw`-`catch` block to check a user provided builder will successfully create a Flux model. This PR ensures that the exception causing the fail is ultimately thrown.

2023-09-04 03:19 UTC, ablaom commented
@OkonSamuel Could you please review this? I've sent you an contributor invitation.

2023-09-04 03:53 UTC, OkonSamuel requested changes

2023-09-04 03:53 UTC, OkonSamuel commented on src/mlj_model_interface.jl
> +        throw(ex)
```suggestion
        rethrow()
```
Lets use rethrow here as its more cleaner

2023-09-04 21:19 UTC, ablaom commented
I've added a test.

2023-09-04 21:40 UTC, ablaom commented
I think we can ignore the nightly fail.

@OkonSamuel Are you happy for a merge?

2023-09-05 05:40 UTC, OkonSamuel approved these changes

2023-09-05 07:31 UTC, merged